config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#root'

  namespace :api, defaults: { format: :json } do
    resources :documents, only: [:index, :show]
  end

  resources :users, only: [:create]
  get 'register', to: 'users#new', as: :new_user

  resource :session, only: [:create, :destroy]
  get 'login', to: 'sessions#new', as: :new_session

  # get '*path', to: 'static_pages#root' # unknown urls to root
end

app/models/document.rb
class Document < ActiveRecord::Base
  validates :title, :body, presence: true
end

app/models/source.rb
class Source < ActiveRecord::Base
  validates :title, :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :username, :password_digest, :session_token, presence: true
  validates :username, uniqueness: { case_sensitive: false, on: :create }
  validates :session_token, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  after_initialize :set_session_token

  # NOTE: returns all users if users does not exist (default scope). possible to compensate with User.is_a? in controller
  # scope :caseless_find, ->(attr, val) { where("lower(#{attr}) = ?", val.downcase).first }

  def self.caseless_find(attr, value)
    where("lower(#{attr}) = ?", value.downcase).first
  end

  def reset_session_token!
    self.session_token = new_token
    self.save!
    self.session_token
  end

  private

  def set_session_token
    self.session_token ||= new_token
  end

  def new_token
    SecureRandom.urlsafe_base64
  end
end

app/controllers/api/documents_controller.rb
class Api::DocumentsController < ApplicationController
  def index
    @documents = Document.all
    render :index
  end

  def show
    @document = Document.find(params[:id])
    render :show
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  private

  def current_user
    return nil if session[:session_token].nil?

    current_user ||=
      User.find_by(session_token: session[:session_token])
  end

  def log_in!(user)
    session[:session_token] = user.reset_session_token!
  end

  def log_out!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def logged_in?
    !!current_user
  end

  def require_account!
    notice = ["You need to be logged in to access this page"]
    redirect_to new_session_url, notice: notice unless logged_in?
  end

  def require_no_account!
    notice = ["You're already logged in"]
    redirect_to root_url, notice: notice if logged_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_no_account!, except: :destroy

  def new
    @user = User.new
    render :new
  end

  def create
    user = User.caseless_find('username', params[:user][:username])

    if user && user.authenticate(params[:user][:password])
      log_in!(user)
      redirect_to root_url
    else
      flash.now[:alert] = ["Invalid username or password"]
      @user = User.new(username: params[:user][:username])
      render :new
    end
  end

  def destroy
    log_out!
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :require_account!, except: [:root]

  def root
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_no_account!

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in!(@user)
      redirect_to root_url
    else
      flash.now[:alert] = @user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    html = <<-HTML
      <input type='hidden'
             name='authenticity_token'
             value='#{form_authenticity_token}'>
    HTML
    html.html_safe
  end
end

app/views/application/_favicon.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= asset_path 'favicon/apple-touch-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= asset_path 'favicon/apple-touch-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= asset_path 'favicon/apple-touch-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= asset_path 'favicon/apple-touch-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= asset_path 'favicon/apple-touch-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= asset_path 'favicon/apple-touch-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= asset_path 'favicon/apple-touch-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= asset_path 'favicon/apple-touch-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path 'favicon/apple-touch-icon-180x180.png' %>">
<link rel="icon" type="image/png" href="<%= asset_path 'favicon/favicon-32x32.png' %>" sizes="32x32">
<link rel="icon" type="image/png" href="<%= asset_path 'favicon/android-chrome-192x192.png' %>" sizes="192x192">
<link rel="icon" type="image/png" href="<%= asset_path 'favicon/favicon-96x96.png' %>" sizes="96x96">
<link rel="icon" type="image/png" href="<%= asset_path 'favicon/favicon-16x16.png' %>" sizes="16x16">
<link rel="manifest" href="<%= asset_path 'favicon/manifest.json' %>">
<link rel="mask-icon" href="<%= asset_path 'favicon/safari-pinned-tab.svg' %>" color="#c23030">
<link rel="shortcut icon" href="<%= asset_path 'favicon/favicon.ico' %>">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-TileImage" content="<%= asset_path 'favicon/mstile-144x144.png' %>">
<meta name="msapplication-config" content="<%= asset_path 'favicon/browserconfig.xml' %>">
<meta name="theme-color" content="#f5f5f5">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang=en>
<head>
  <title>proto-typist</title>

  <%= render 'favicon' %>

  <meta name="viewport" content="width=device-width,initial-scale=1">

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<!--   <div temp="header">
    &nbsp;
    <% if logged_in? %>
      <%= current_user.username %>
      <%= link_to "log out", session_url, method: :delete %>
    <% else %>
      <%= link_to "register", new_user_url %>
      <%= link_to "log in", new_session_url %>
    <% end %>
    &nbsp;
    <%= link_to "home", root_url %>
  </div>
  <br>
  <div temp="errors">
    <% if flash.is_a?(Array) %>
      <% flash.each do |name, msg| -%>
        <%= content_tag :div, msg, class: name %>
      <% end %>
      <br>
    <% end %>
  </div> -->

  <%= yield %>

</body>
</html>

app/views/users/new.html.erb
<form action="<%= users_url %>" method="POST">
  <%= auth_token %>

  <label for="user_username">Username</label>
  <input type="text"
         name="user[username]"
         value="<%= @user.username %>"
         id="user_username">

  <label for="user_password">Password</label>
  <input type="password" name="user[password]" id="user_password">

  <label for="user_password_confirmation">Confirm</label>
  <input type="password"
         name="user[password_confirmation]"
         id="user_password_confirmation">

  <input type="submit" value="Register">
</form>